#!/bin/sh

alias ls='ls --color=auto'
alias o='xdg-open'

alias evim='pushd $DOTFILES/nvim; vim init.lua; popd'
alias vim='nvim'
alias v='nvim'
alias vs='vim -S .session.vim'
alias vc='vim ~/.dotfiles'
alias ealias='vim ~/Documents/bash_alias'
alias so='source ~/Documents/bash_alias'
alias n='vim ~/Documents/neorg/scratchbuff.norg'
alias dot='pushd ~/.dotfiles'

alias f='target="$(cat $FAVDIR | fzf --height=40% --layout=reverse)"; [[ -n $target ]] && cd $target'
alias fa='favorite -a'
alias fx='target="$(cat $FAVDIR | fzf --height=40% --layout=reverse)"; [[ -n $target ]] && favorite -d $target'
alias fl='bat $FAVDIR'
alias efav='vim $FAVDIR'

alias tree='tree -C'
alias t='tree -L 1'
alias val='valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s'
alias mocp='mocp -T /usr/share/moc/themes/nightly_theme'

alias getXDisplay='xrandr | grep \ connected | cut -f 1 -d\ '
alias Xbrightness='xrandr --output $(getDisplay) --brightness $1'

alias lynx='lynx -cookie_file=.cache/cookies -accept_all_cookies -vikeys duckduckgo.com'
alias ipub='echo "$(curl -s ipinfo.io/ip)"'
alias modelio='GTK_THEME=Adwaita:ligth /opt/modelio/modelio'

alias cpost='curl -X POST -H "Content-Type: application/json"'

alias todo='vim ~/Documents/neorg/todo.neorg'

alias h='cut -d";" -f2 <<< $(cat ~/.zsh_history) | fzf'
