require('g.global_settings')
require('g.plugins')
require('g.cmp_settings')
require('g.tree_sitter')
require('g.lsp_settings')
require('g.dap_setting')
require('g.telescope')
require('g.keymaps')
require('g.themes')
require('g.lua_line')
require('g.startify')

require('refactoring').setup({})
