require('g.plugins')
require('g.tree_sitter')
require('g.global_settings')
require('g.lsp_settings')
require('g.keymaps')
require('g.themes')
require('g.lua_line')
require('g.startify')
require('g.cmp')

require('refactoring').setup({})
