#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$XDG_DATA_HOME/cargo/bin:$PATH
export PATH=$XDG_DATA_HOME/go/bin:$PATH
export GOPATH=$XDG_DATA_HOME/go
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
